# Generated by Django 4.0.6 on 2022-07-09 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sounds', '0001_initial'),
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=2048, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delay',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('duration', models.DurationField()),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='TextBox',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('content', models.CharField(max_length=2048)),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='PlaySoundEffect',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('sound_effect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sounds.soundeffect')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='FullscreenTextBox',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('content', models.CharField(max_length=4096)),
                ('speaker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='characters.character')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='ChangeCharacters',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('character_one', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events_used_in_as_char_one', to='characters.character')),
                ('character_one_expression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events_used_in_as_char_two', to='characters.character')),
                ('character_two', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events_used_in_as_char_expression_one', to='characters.character')),
                ('character_two_expression', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events_used_in_as_char_expression_two', to='characters.character')),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='ChangeAudio',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sounds.audiotrack')),
            ],
            bases=('events.event',),
        ),
    ]
